app:
  env: dev
  dcenter: 1
  snode: 1
  dtask: replace_to_dtask_host

logging:
  config: classpath:log4j2-dev.xml

server:
  tomcat:
    accesslog:
      enabled: false

management:
  endpoint:
    httptrace:
      enabled: false
  endpoints:
    web:
      base-path: /holy
      exposure:
        include: metrics,loggers,threaddump



